According to Derek Banas: NumPy is an amazing scientific computing library that is used by numerous other Python Data Science libraries. NumPy contains many mathematical, array and string functions that are extremely useful. Along with all the basic math functions you'll also find them for Linear Algebra, Statistics, Simulation, etc.

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.


# Numpy Arrrays

## Creating Arrays

In [4]:
# To access NumPy and its functions import it in your Python code like this:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [24]:
list1 = [1, 2, 3, 4, 5, 6] # regular python list

# one dimensional array with numpy
np_array_1 = np.array(list1, dtype=np.int8)

np_array_1

list2 = [[1, 2, 3], [4, 5, 6]] # regular python list

# multidimensional array with numpy
np_array_2 = np.array(list2)
np_array_2

# range of values (start_value, stop_value - 1, step)
np.arange(1, 20, 2)

# generating floats
np.linspace(0, 5, 5)
# generate zero array
np.zeros(4)
# multidimensional (4, 5)
np.zeros((4,5))
# generating ones
np.ones((3,3))
#number of items
np_array_2.size
# generating arrays with default values
np_arr_2 = np.array([1,2,3,4,5,6])
np_arr_2
np_arr_3 = np.array([[1,2,3],[4,5,6]])
np_arr_3

# getting the array data type
np_arr_3.dtype

dtype('int32')

Data types in numpy are:
- Data Types
- Boolean : np.bool_
- Char : np.byte
- Short : np.short
- Integer : np.short
- Long : np.int_
- Float : np.single & np.float32
- Double : np.double & np.float64
- np.int8 : -128 to 127
- np.int16 : -32768 to 32767
- np.int32 : -2147483648 to 2147483647
- np.int64 : -9223372036854775808 to 9223372036854775807

In [26]:
# generate random arrays start, end and amount of values. 
np.random.randint(10, 50, 5)

# generate random arrays start, end and amount of values. multidimensional
np.random.randint(10, 50, (3,4))

array([[18, 24, 28, 32],
       [32, 24, 25, 34],
       [38, 21, 42, 39]])

In [28]:
# if i want to know more about a funtion I can insert a ? in front of the function
np.random.randint?

# Slicing and indexes

In [29]:
np_arr_3

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# changing a value in a array
np_arr_3[0, 0] = 5

In [33]:
np_arr_3

array([[5, 2, 3],
       [4, 5, 6]])

In [34]:
# different way to change it first is the index, second is the value
np_arr_3.itemset((0, 1), 1) 

In [35]:
np_arr_3

array([[5, 1, 3],
       [4, 5, 6]])

In [37]:
# getting the shape of any array (overall size)
rows, cols = np_arr_3.shape
rows
cols

3

In [41]:
# getting a value from np array
np_arr_3[0, 0]

5

In [40]:
np_arr_3.item(0,0)

5

In [47]:
# getting specifics indexes
np.take(np_array_1, [0, 2, 5])

array([1, 3, 6], dtype=int8)

In [49]:
print("Array 1: ", np_arr_3)
np.take(np_arr_3, [0, 1, 4])

Array 1:  [[5 1 3]
 [4 5 6]]


array([5, 1, 5])

In [50]:
# replacing values array working with, indexes want to update and new values
np.put(np_arr_3, [0, 1, 4], [10, 10, 3])
print("Array 1: ", np_arr_3)

Array 1:  [[10 10  3]
 [ 4  3  6]]


In [55]:
# slicing array
# living blank before : gives us the start of the array
np_array_1[:5:2]

array([1, 3, 5], dtype=int8)

In [66]:
# slicing multidimensional array
np_arr_3
np_arr_3[:, 1] # all lines, col 1

array([10,  3])

In [68]:
# flip array
np_arr_3[::-1]

array([[ 4,  3,  6],
       [10, 10,  3]])

In [72]:
# get even values
even_values = np_arr_3[np_arr_3 % 2 == 0]
even_values

array([10, 10,  4,  6])

In [73]:
# getting values greater than 5
np_arr_3[np_arr_3 > 5]


array([10, 10,  6])

In [74]:
np_arr_3[(np_arr_3 > 5) & (np_arr_3 < 9)] #  &, |, and so on

array([6])

In [75]:
# getting only unique values
np.unique(np_arr_3)

array([ 3,  4,  6, 10])

# Reshaping Array

In [89]:
# reshaping in a single unidimensional array

np_arr_3
np_arr_3.reshape((1, 6))

array([[10, 10,  3,  4,  3,  6]])

In [86]:
# resizing an array
np.resize(np_arr_3, (2, 5))

array([[10, 10,  3,  4,  3],
       [ 6, 10, 10,  3,  4]])

In [97]:
# transpose the array
np_arr_3.transpose()

array([[10,  4],
       [10,  3],
       [ 3,  6]])

In [95]:
np_arr_3

array([[10, 10,  3],
       [ 4,  3,  6]])

In [98]:
# awap the axis
np_arr_3.swapaxes(0, 1)

array([[10,  4],
       [10,  3],
       [ 3,  6]])

In [99]:
# flatten the array
np_arr_3.flatten()

array([10, 10,  3,  4,  3,  6])

In [100]:
# flatten in col order the array
np_arr_3.flatten('F')

array([10,  4, 10,  3,  3,  6])

In [102]:
# sort array (sort row)
np_arr_3.sort(axis=1)
np_arr_3

array([[ 3, 10, 10],
       [ 3,  4,  6]])

In [103]:
# sort array (sort col)
np_arr_3.sort(axis=0)
np_arr_3

array([[ 3,  4,  6],
       [ 3, 10, 10]])

# Stacking and Splitting

In [104]:
random_array_1 = np.random.randint(10, size=(2,2))
print("array 1: ", random_array_1)
random_array_2 = np.random.randint(10, size=(2,2))
print("array 2: ", random_array_2)

array 1:  [[2 2]
 [5 1]]
array 2:  [[1 5]
 [2 0]]


In [105]:
np.hstack((random_array_1, random_array_2))

array([[2, 2, 1, 5],
       [5, 1, 2, 0]])

In [112]:
# delete in a array
np_arr = np.delete(random_array_1, 1, 0)
np_arr

array([[2, 2]])

In [116]:
# combining array (column)
np.column_stack((random_array_1, random_array_2))

array([[2, 2, 1, 5],
       [5, 1, 2, 0]])

In [124]:
# combining array (row)
np.row_stack((random_array_1, random_array_2))

array([[2, 2],
       [5, 1],
       [1, 5],
       [2, 0]])

In [120]:
random_array_3 = np.random.randint(0, 10, size=(2,10))
print("Array 3: ", random_array_3)

Array 3:  [[4 0 3 4 9 9 4 6 4 2]
 [6 8 2 0 1 6 3 3 4 4]]


In [125]:
np.hsplit(random_array_3, (2, 4))

[array([[4, 0],
        [6, 8]]), array([[3, 4],
        [2, 0]]), array([[9, 9, 4, 6, 4, 2],
        [1, 6, 3, 3, 4, 4]])]

# Copying

In [128]:
cp_arr_1 = np.random.randint(0, 1, size=(2,2))
cp_arr_2 = cp_arr_1 # pointing to the same array

cp_arr_3 = cp_arr_1.view()
cp_arr_4 = cp_arr_1.copy()