# Basic Math

In [10]:
import numpy as np
from numpy import random
import matplotlib.pylab as plt
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 3, 4, 5])
                 
arr_3 - arr_4                

array([-1, -1, -1, -1])

In [5]:
arr_3 * arr_4         

array([ 2,  6, 12, 20])

In [6]:
arr_3 + arr_4         

array([3, 5, 7, 9])

In [7]:
arr_3 / arr_4         

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [13]:
arr_5 = random.randint(100, size=(4))
arr_6 = random.randint(100, size=(2,3))

# float random
random.rand(4)

# getting a random value of an array
random.choice(arr_6.flatten())


81

In [14]:
# sum values
arr_3.sum()

10

In [15]:
# sum values cols
arr_3.sum(axis=0)

10

In [18]:
# accumulative sum rows
print(arr_6)
arr_6.cumsum() 

[[16 73 78]
 [81  3 46]]


array([ 16,  89, 167, 248, 251, 297], dtype=int32)

In [19]:
# accumulative sum cols
print(arr_6)
arr_6.cumsum(axis=0) 

[[16 73 78]
 [81  3 46]]


array([[ 16,  73,  78],
       [ 97,  76, 124]], dtype=int32)

In [21]:
arr_6.min(axis=1) #row

array([16,  3])

In [22]:
arr_6.min(axis=0) #col

array([16,  3, 46])

In [24]:
print(arr_3)
np.add(arr_3, 5)

[1 2 3 4]


array([6, 7, 8, 9])

In [25]:
np.add(arr_3, arr_4)

array([3, 5, 7, 9])

In [26]:
np.multiply(arr_3, arr_4)

array([ 2,  6, 12, 20])

In [27]:
np.subtract(arr_3, arr_4)

array([-1, -1, -1, -1])

In [28]:
np.divide(arr_3, arr_4)

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [30]:
arr_a1 = np.array([[1,2], [3, 4]])
arr_a2 = np.array([[2,4], [6, 9]])

In [31]:
np.remainder(arr_a1, arr_a2)

array([[1, 2],
       [3, 4]], dtype=int32)

In [32]:
np.power(arr_a1, arr_a2)

array([[     1,     16],
       [   729, 262144]], dtype=int32)

In [34]:
np.sqrt(arr_a1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [35]:
np.cbrt(arr_a1) #cube root

array([[1.        , 1.25992105],
       [1.44224957, 1.58740105]])

In [37]:
np.absolute([-1, -2])

array([1, 2])

In [38]:
np.exp(arr_a1)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [39]:
np.log(arr_a1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [40]:
np.log2(arr_a1)

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [41]:
np.log10(arr_a1)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [42]:
# getting greatest common divisor
np.gcd.reduce([9, 12, 15])

3

In [44]:
# getting lowest common model
np.lcm.reduce([9, 12, 15])

180

In [45]:
np.floor([1.2, 2.5])

array([1., 2.])

In [46]:
np.ceil([1.2, 2.5])

array([2., 3.])

In [47]:
sq_arr = np.arange(6) ** 2
sq_arr

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [50]:
arr_7 = np.random.randint(10, size=(5,3))
print(arr_7)
mc_index = arr_7.argmax(axis=0) # getting index of max numbers
mc_index

[[0 0 3]
 [4 0 1]
 [2 0 9]
 [4 2 2]
 [8 5 3]]


array([4, 4, 2], dtype=int64)